# 📊 **Stock Market Data Collection using Alpha Vantage API**

This project focuses on collecting historical stock market data for **NSE and BSE** using the Alpha Vantage API.

## 🎯 **Objectives**
- Fetch stock data using API
- Convert JSON to structured DataFrame
- Perform data preprocessing
- Save clean datasets for further modeling

### **Secure API Key Setup using Google Drive**

In [ ]:
API_KEY_PATH = "/content/drive/MyDrive/api_key.txt"

with open (API_KEY_PATH, "r") as file:
  API_KEY = file.read().strip()

print ("API Key Loaded Successfully")

API Key Loaded Successfully

Verify

In [ ]:
print (API_KEY[:3] + "*******")

AYI*******

### **Installing, Updating and Importing the Libraries**

In [ ]:
!pip install --upgrade pandas requests

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Collecting pandas
  Downloading pandas-3.0.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 1.7 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Collecting requests
  Downloading requests-2.33.0-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 51.8 MB/s eta 0:00:00
Downloading requests-2.33.0-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.0/65.0 kB 3.8 MB/s eta 0:00:00
Installing collected packages: requests, pandas
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.1 which is incompatible.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.33.0 which is incompatible.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, but you have pandas 3.0.1 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.1 which is incompatible.
db-dtypes 1.5.0 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.1 which is incompatible.
Successfully installed pandas-3.0.1 requests-2.33.0

In [ ]:
import requests
import pandas as pd
import time

## **Defining Fetch Function**

In [ ]:
def fetch_stock_data(symbol):
    url = f"https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={symbol}&apikey={API_KEY}&outputsize=compact"

    response = requests.get(url)
    data = response.json()

    print("FULL RESPONSE:", data)

    if "Time Series (Daily)" not in data:
        print(f"Error for {symbol}")
        return None

    df = pd.DataFrame.from_dict(data["Time Series (Daily)"], orient='index')

    df.columns = ["open", "high", "low", "close", "volume"]
    df.index = pd.to_datetime(df.index)
    df = df.sort_index()

    return df

### **Fetching NSE**

In [ ]:
df_nse = fetch_stock_data("HDB")
df_nse.head()

FULL RESPONSE: {'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes', '2. Symbol': 'HDB', '3. Last Refreshed': '2026-03-25', '4. Output Size': 'Compact', '5. Time Zone': 'US/Eastern'}, 'Time Series (Daily)': {'2026-03-25': {'1. open': '26.0000', '2. high': '26.3800', '3. low': '25.7500', '4. close': '25.8100', '5. volume': '20723415'}, '2026-03-24': {'1. open': '25.2300', '2. high': '25.5300', '3. low': '25.0800', '4. close': '25.1200', '5. volume': '13980404'}, '2026-03-23': {'1. open': '25.1600', '2. high': '25.6900', '3. low': '24.7400', '4. close': '25.4000', '5. volume': '19046686'}, '2026-03-20': {'1. open': '26.1100', '2. high': '26.1400', '3. low': '25.3900', '4. close': '25.3900', '5. volume': '14991502'}, '2026-03-19': {'1. open': '25.8950', '2. high': '27.0000', '3. low': '25.4800', '4. close': '26.1400', '5. volume': '32970355'}, '2026-03-18': {'1. open': '28.4600', '2. high': '28.6850', '3. low': '26.4150', '4. close': '26.6200', '5. volume': '18213000'}, '2026-03-17': {'1. open': '29.0600', '2. high': '29.1300', '3. low': '28.6500', '4. close': '28.7100', '5. volume': '6511075'}, '2026-03-16': {'1. open': '28.8400', '2. high': '29.2900', '3. low': '28.8400', '4. close': '28.9900', '5. volume': '7707381'}, '2026-03-13': {'1. open': '28.3500', '2. high': '28.5100', '3. low': '28.1900', '4. close': '28.2300', '5. volume': '8735994'}, '2026-03-12': {'1. open': '28.4600', '2. high': '28.6000', '3. low': '28.0500', '4. close': '28.3900', '5. volume': '12057912'}, '2026-03-11': {'1. open': '29.0400', '2. high': '29.1300', '3. low': '28.3150', '4. close': '28.5000', '5. volume': '11629868'}, '2026-03-10': {'1. open': '29.7200', '2. high': '29.9800', '3. low': '29.4500', '4. close': '29.4800', '5. volume': '5913401'}, '2026-03-09': {'1. open': '28.9300', '2. high': '29.8200', '3. low': '28.6500', '4. close': '29.7200', '5. volume': '8140897'}, '2026-03-06': {'1. open': '30.0100', '2. high': '30.0100', '3. low': '29.4300', '4. close': '29.4700', '5. volume': '10790530'}, '2026-03-05': {'1. open': '30.6400', '2. high': '30.8500', '3. low': '30.2350', '4. close': '30.3900', '5. volume': '10444843'}, '2026-03-04': {'1. open': '30.8400', '2. high': '30.9900', '3. low': '30.6550', '4. close': '30.7900', '5. volume': '6116236'}, '2026-03-03': {'1. open': '30.5100', '2. high': '30.9799', '3. low': '30.4500', '4. close': '30.8500', '5. volume': '9262957'}, '2026-03-02': {'1. open': '31.2700', '2. high': '31.8200', '3. low': '31.0400', '4. close': '31.5600', '5. volume': '6003121'}, '2026-02-27': {'1. open': '31.7800', '2. high': '31.8700', '3. low': '31.5300', '4. close': '31.8500', '5. volume': '5256281'}, '2026-02-26': {'1. open': '32.1500', '2. high': '32.2250', '3. low': '31.9200', '4. close': '32.0000', '5. volume': '4207786'}, '2026-02-25': {'1. open': '32.1900', '2. high': '32.5500', '3. low': '32.0150', '4. close': '32.1500', '5. volume': '5677980'}, '2026-02-24': {'1. open': '32.4000', '2. high': '32.4200', '3. low': '31.5550', '4. close': '32.2300', '5. volume': '8442876'}, '2026-02-23': {'1. open': '33.2200', '2. high': '33.4100', '3. low': '32.6650', '4. close': '32.6900', '5. volume': '4795630'}, '2026-02-20': {'1. open': '32.7500', '2. high': '33.2858', '3. low': '32.5100', '4. close': '33.0900', '5. volume': '7115254'}, '2026-02-19': {'1. open': '32.8200', '2. high': '33.0074', '3. low': '32.5837', '4. close': '32.7000', '5. volume': '3532766'}, '2026-02-18': {'1. open': '32.7400', '2. high': '33.3600', '3. low': '32.6700', '4. close': '33.3500', '5. volume': '5047805'}, '2026-02-17': {'1. open': '32.9600', '2. high': '33.0100', '3. low': '32.6550', '4. close': '32.8100', '5. volume': '8213337'}, '2026-02-13': {'1. open': '32.3500', '2. high': '32.5300', '3. low': '32.1150', '4. close': '32.5200', '5. volume': '9085319'}, '2026-02-12': {'1. open': '33.1800', '2. high': '33.3000', '3. low': '32.7500', '4. close': '32.8600', '5. volume': '6803795'}, '2026-02-11': {'1. open': '33.5850', '2. high': '33.7300', '3. low': '33.1200', '4. close': '33.2100', '5. volume': '7806111'}, '2026-02-10': {'1. open': '33.8500', '2. high': '34.0565', '3. low': '33.6600', '4. close': '33.9900', '5. volume': '6454394'}, '2026-02-09': {'1. open': '33.5800', '2. high': '33.9350', '3. low': '33.2800', '4. close': '33.8600', '5. volume': '6531495'}, '2026-02-06': {'1. open': '33.9900', '2. high': '34.4600', '3. low': '33.6700', '4. close': '34.4600', '5. volume': '8547440'}, '2026-02-05': {'1. open': '33.7300', '2. high': '34.0800', '3. low': '33.5500', '4. close': '33.9900', '5. volume': '5034642'}, '2026-02-04': {'1. open': '33.9100', '2. high': '34.0575', '3. low': '33.5600', '4. close': '33.9500', '5. volume': '7082436'}, '2026-02-03': {'1. open': '33.5100', '2. high': '34.4600', '3. low': '33.3250', '4. close': '33.5700', '5. volume': '9553916'}, '2026-02-02': {'1. open': '32.2200', '2. high': '33.9450', '3. low': '32.0800', '4. close': '33.7900', '5. volume': '9850114'}, '2026-01-30': {'1. open': '32.2700', '2. high': '32.5000', '3. low': '32.0600', '4. close': '32.3800', '5. volume': '4608846'}, '2026-01-29': {'1. open': '32.5400', '2. high': '32.5800', '3. low': '32.2150', '4. close': '32.5500', '5. volume': '5929552'}, '2026-01-28': {'1. open': '32.4800', '2. high': '32.4800', '3. low': '32.1200', '4. close': '32.3100', '5. volume': '9603158'}, '2026-01-27': {'1. open': '32.4900', '2. high': '32.6600', '3. low': '32.2846', '4. close': '32.4400', '5. volume': '3900473'}, '2026-01-26': {'1. open': '32.1500', '2. high': '32.3100', '3. low': '32.0400', '4. close': '32.1500', '5. volume': '5042189'}, '2026-01-23': {'1. open': '31.8900', '2. high': '32.0600', '3. low': '31.3400', '4. close': '32.0600', '5. volume': '5414376'}, '2026-01-22': {'1. open': '31.9400', '2. high': '32.2800', '3. low': '31.9400', '4. close': '32.1000', '5. volume': '5594818'}, '2026-01-21': {'1. open': '32.0900', '2. high': '32.1800', '3. low': '31.7700', '4. close': '32.1300', '5. volume': '6985349'}, '2026-01-20': {'1. open': '32.1800', '2. high': '32.6620', '3. low': '31.9800', '4. close': '32.3400', '5. volume': '6418176'}, '2026-01-16': {'1. open': '32.5400', '2. high': '32.7800', '3. low': '32.4600', '4. close': '32.6500', '5. volume': '4782791'}, '2026-01-15': {'1. open': '32.9300', '2. high': '32.9300', '3. low': '32.2900', '4. close': '32.5100', '5. volume': '6726418'}, '2026-01-14': {'1. open': '33.0000', '2. high': '33.2600', '3. low': '32.8300', '4. close': '32.9200', '5. volume': '4616244'}, '2026-01-13': {'1. open': '33.5100', '2. high': '33.5500', '3. low': '32.8900', '4. close': '33.2000', '5. volume': '4211345'}, '2026-01-12': {'1. open': '33.0600', '2. high': '33.5850', '3. low': '32.9600', '4. close': '33.5200', '5. volume': '3690888'}, '2026-01-09': {'1. open': '33.1000', '2. high': '33.2350', '3. low': '32.9700', '4. close': '33.1000', '5. volume': '5371160'}, '2026-01-08': {'1. open': '33.2000', '2. high': '33.5050', '3. low': '33.1100', '4. close': '33.3900', '5. volume': '15963346'}, '2026-01-07': {'1. open': '33.5750', '2. high': '33.9500', '3. low': '33.1800', '4. close': '33.2000', '5. volume': '13949347'}, '2026-01-06': {'1. open': '34.1400', '2. high': '34.3128', '3. low': '33.4200', '4. close': '33.4300', '5. volume': '8483079'}, '2026-01-05': {'1. open': '35.7500', '2. high': '35.8000', '3. low': '34.1500', '4. close': '34.1700', '5. volume': '9159913'}, '2026-01-02': {'1. open': '36.6500', '2. high': '36.7300', '3. low': '36.1300', '4. close': '36.4800', '5. volume': '3247643'}, '2025-12-31': {'1. open': '36.5000', '2. high': '36.6550', '3. low': '36.3100', '4. close': '36.5400', '5. volume': '1979717'}, '2025-12-30': {'1. open': '36.3600', '2. high': '36.6600', '3. low': '36.3200', '4. close': '36.4400', '5. volume': '2780743'}, '2025-12-29': {'1. open': '36.0700', '2. high': '36.4350', '3. low': '36.0200', '4. close': '36.3400', '5. volume': '2560111'}, '2025-12-26': {'1. open': '36.1700', '2. high': '36.4600', '3. low': '36.1100', '4. close': '36.4600', '5. volume': '2261333'}, '2025-12-24': {'1. open': '36.1600', '2. high': '36.4400', '3. low': '36.1550', '4. close': '36.4000', '5. volume': '1536814'}, '2025-12-23': {'1. open': '36.3400', '2. high': '36.5650', '3. low': '36.1800', '4. close': '36.2800', '5. volume': '2471791'}, '2025-12-22': {'1. open': '35.8600', '2. high': '36.3900', '3. low': '35.7800', '4. close': '36.2900', '5. volume': '3060164'}, '2025-12-19': {'1. open': '35.4700', '2. high': '36.1600', '3. low': '35.3400', '4. close': '35.8900', '5. volume': '4805837'}, '2025-12-18': {'1. open': '35.0400', '2. high': '35.4700', '3. low': '35.0400', '4. close': '35.1500', '5. volume': '2397157'}, '2025-12-17': {'1. open': '35.3300', '2. high': '35.3900', '3. low': '34.8600', '4. close': '35.1300', '5. volume': '3244348'}, '2025-12-16': {'1. open': '35.6900', '2. high': '35.7800', '3. low': '35.2800', '4. close': '35.3000', '5. volume': '3599346'}, '2025-12-15': {'1. open': '35.8500', '2. high': '36.1500', '3. low': '35.5700', '4. close': '35.9900', '5. volume': '3475734'}, '2025-12-12': {'1. open': '35.7600', '2. high': '35.9700', '3. low': '35.5800', '4. close': '35.8900', '5. volume': '2994586'}, '2025-12-11': {'1. open': '35.5500', '2. high': '36.0200', '3. low': '35.4400', '4. close': '35.8300', '5. volume': '3801302'}, '2025-12-10': {'1. open': '34.8400', '2. high': '35.5500', '3. low': '34.8300', '4. close': '35.4200', '5. volume': '2585388'}, '2025-12-09': {'1. open': '35.0800', '2. high': '35.4000', '3. low': '34.9250', '4. close': '35.1700', '5. volume': '3131725'}, '2025-12-08': {'1. open': '35.7300', '2. high': '35.7300', '3. low': '35.0000', '4. close': '35.1600', '5. volume': '4113196'}, '2025-12-05': {'1. open': '36.1200', '2. high': '36.1200', '3. low': '35.6000', '4. close': '35.7200', '5. volume': '3101320'}, '2025-12-04': {'1. open': '35.8200', '2. high': '36.0900', '3. low': '35.7350', '4. close': '35.9600', '5. volume': '2412313'}, '2025-12-03': {'1. open': '36.1900', '2. high': '36.3500', '3. low': '35.8600', '4. close': '35.8700', '5. volume': '2896664'}, '2025-12-02': {'1. open': '35.4000', '2. high': '35.8650', '3. low': '35.4000', '4. close': '35.8400', '5. volume': '3951528'}, '2025-12-01': {'1. open': '36.7000', '2. high': '36.7800', '3. low': '35.1550', '4. close': '35.4400', '5. volume': '8691208'}, '2025-11-28': {'1. open': '36.8200', '2. high': '37.0100', '3. low': '36.6900', '4. close': '36.8200', '5. volume': '1572858'}, '2025-11-26': {'1. open': '36.5000', '2. high': '36.7650', '3. low': '36.4250', '4. close': '36.6300', '5. volume': '2228081'}, '2025-11-25': {'1. open': '36.1250', '2. high': '36.2200', '3. low': '35.5500', '4. close': '36.1800', '5. volume': '2708274'}, '2025-11-24': {'1. open': '36.6400', '2. high': '36.6600', '3. low': '36.2700', '4. close': '36.3800', '5. volume': '3874283'}, '2025-11-21': {'1. open': '36.7100', '2. high': '37.0500', '3. low': '36.4300', '4. close': '36.6700', '5. volume': '4854815'}, '2025-11-20': {'1. open': '36.8500', '2. high': '37.3450', '3. low': '36.8200', '4. close': '36.8800', '5. volume': '4286600'}, '2025-11-19': {'1. open': '37.0100', '2. high': '37.1200', '3. low': '36.4250', '4. close': '36.4600', '5. volume': '2994188'}, '2025-11-18': {'1. open': '36.7300', '2. high': '37.2900', '3. low': '36.6000', '4. close': '37.1300', '5. volume': '4245306'}, '2025-11-17': {'1. open': '36.4100', '2. high': '37.1050', '3. low': '36.4100', '4. close': '36.8400', '5. volume': '3954756'}, '2025-11-14': {'1. open': '36.2700', '2. high': '36.5000', '3. low': '35.9600', '4. close': '36.4400', '5. volume': '2389826'}, '2025-11-13': {'1. open': '36.4000', '2. high': '36.4000', '3. low': '36.1700', '4. close': '36.2700', '5. volume': '3739890'}, '2025-11-12': {'1. open': '36.3800', '2. high': '36.5500', '3. low': '36.2500', '4. close': '36.4800', '5. volume': '3588687'}, '2025-11-11': {'1. open': '36.2700', '2. high': '36.7500', '3. low': '36.1800', '4. close': '36.7000', '5. volume': '2600905'}, '2025-11-10': {'1. open': '35.8200', '2. high': '36.1400', '3. low': '35.6500', '4. close': '36.0700', '5. volume': '2416990'}, '2025-11-07': {'1. open': '35.7600', '2. high': '36.1400', '3. low': '35.6050', '4. close': '35.8100', '5. volume': '3479151'}, '2025-11-06': {'1. open': '35.9500', '2. high': '35.9500', '3. low': '35.5350', '4. close': '35.6900', '5. volume': '4087544'}, '2025-11-05': {'1. open': '36.1400', '2. high': '36.1900', '3. low': '35.5100', '4. close': '35.8300', '5. volume': '4879543'}, '2025-11-04': {'1. open': '36.2300', '2. high': '36.3700', '3. low': '35.9100', '4. close': '36.2400', '5. volume': '3778781'}, '2025-11-03': {'1. open': '36.3100', '2. high': '36.7200', '3. low': '36.2500', '4. close': '36.5000', '5. volume': '2905007'}, '2025-10-31': {'1. open': '36.3200', '2. high': '36.3800', '3. low': '35.9300', '4. close': '36.2200', '5. volume': '3500574'}, '2025-10-30': {'1. open': '36.8000', '2. high': '36.9400', '3. low': '36.5600', '4. close': '36.8800', '5. volume': '4950856'}}}

               open     high      low    close   volume
2025-10-30  36.8000  36.9400  36.5600  36.8800  4950856
2025-10-31  36.3200  36.3800  35.9300  36.2200  3500574
2025-11-03  36.3100  36.7200  36.2500  36.5000  2905007
2025-11-04  36.2300  36.3700  35.9100  36.2400  3778781
2025-11-05  36.1400  36.1900  35.5100  35.8300  4879543

In [ ]:
df_bse = fetch_stock_data("HDFCBANK.BSE")
df_bse.head()

FULL RESPONSE: {'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes', '2. Symbol': 'HDFCBANK.BSE', '3. Last Refreshed': '2026-03-25', '4. Output Size': 'Compact', '5. Time Zone': 'US/Eastern'}, 'Time Series (Daily)': {'2026-03-25': {'1. open': '769.8000', '2. high': '794.8000', '3. low': '768.4000', '4. close': '781.7000', '5. volume': '4057883'}, '2026-03-24': {'1. open': '767.7500', '2. high': '772.6000', '3. low': '747.7000', '4. close': '765.1500', '5. volume': '2829026'}, '2026-03-23': {'1. open': '766.9500', '2. high': '768.3000', '3. low': '740.9500', '4. close': '743.7500', '5. volume': '4002930'}, '2026-03-20': {'1. open': '788.0000', '2. high': '794.0000', '3. low': '778.6000', '4. close': '780.4500', '5. volume': '5028824'}, '2026-03-19': {'1. open': '776.0000', '2. high': '815.6000', '3. low': '772.0000', '4. close': '799.7000', '5. volume': '7214369'}, '2026-03-18': {'1. open': '845.2500', '2. high': '846.8000', '3. low': '831.7000', '4. close': '842.9500', '5. volume': '1101070'}, '2026-03-17': {'1. open': '847.0000', '2. high': '848.8000', '3. low': '835.1500', '4. close': '845.8500', '5. volume': '561733'}, '2026-03-16': {'1. open': '816.6000', '2. high': '844.4500', '3. low': '815.6000', '4. close': '840.5000', '5. volume': '1912631'}, '2026-03-13': {'1. open': '818.0000', '2. high': '824.1500', '3. low': '812.0000', '4. close': '817.0000', '5. volume': '1204483'}, '2026-03-12': {'1. open': '822.2500', '2. high': '836.6500', '3. low': '820.0000', '4. close': '832.5000', '5. volume': '2503832'}, '2026-03-11': {'1. open': '847.9500', '2. high': '849.1000', '3. low': '827.8000', '4. close': '834.0000', '5. volume': '1127878'}, '2026-03-10': {'1. open': '847.6000', '2. high': '857.0000', '3. low': '842.1000', '4. close': '849.1000', '5. volume': '1212888'}, '2026-03-09': {'1. open': '829.9000', '2. high': '842.7500', '3. low': '823.0000', '4. close': '839.2000', '5. volume': '1782240'}, '2026-03-06': {'1. open': '869.9000', '2. high': '871.9500', '3. low': '855.1500', '4. close': '857.1000', '5. volume': '3384852'}, '2026-03-05': {'1. open': '871.1000', '2. high': '881.4000', '3. low': '864.0000', '4. close': '878.0500', '5. volume': '1783557'}, '2026-03-04': {'1. open': '847.0000', '2. high': '879.2500', '3. low': '847.0000', '4. close': '868.4000', '5. volume': '1684336'}, '2026-03-02': {'1. open': '871.0500', '2. high': '887.7500', '3. low': '871.0500', '4. close': '881.7500', '5. volume': '3167635'}, '2026-02-27': {'1. open': '898.8500', '2. high': '900.0000', '3. low': '885.2500', '4. close': '887.4000', '5. volume': '2398282'}, '2026-02-26': {'1. open': '910.3000', '2. high': '912.0000', '3. low': '895.4500', '4. close': '898.8500', '5. volume': '1467353'}, '2026-02-25': {'1. open': '911.9500', '2. high': '916.0000', '3. low': '903.1000', '4. close': '907.7500', '5. volume': '1076533'}, '2026-02-24': {'1. open': '923.9000', '2. high': '926.9500', '3. low': '909.4500', '4. close': '910.7000', '5. volume': '1022055'}, '2026-02-23': {'1. open': '912.1500', '2. high': '925.7000', '3. low': '912.1500', '4. close': '923.8500', '5. volume': '2800825'}, '2026-02-20': {'1. open': '909.9500', '2. high': '918.0000', '3. low': '908.4000', '4. close': '911.9000', '5. volume': '921385'}, '2026-02-19': {'1. open': '929.9500', '2. high': '929.9500', '3. low': '912.3500', '4. close': '916.0500', '5. volume': '1035509'}, '2026-02-18': {'1. open': '923.0000', '2. high': '925.9500', '3. low': '919.8000', '4. close': '924.6500', '5. volume': '552660'}, '2026-02-17': {'1. open': '922.9500', '2. high': '928.2500', '3. low': '918.6500', '4. close': '925.6000', '5. volume': '621194'}, '2026-02-16': {'1. open': '905.7000', '2. high': '929.4000', '3. low': '902.2500', '4. close': '925.4500', '5. volume': '5217597'}, '2026-02-13': {'1. open': '916.8500', '2. high': '928.1500', '3. low': '901.5500', '4. close': '905.6500', '5. volume': '4105639'}, '2026-02-12': {'1. open': '926.0500', '2. high': '928.7000', '3. low': '918.5000', '4. close': '920.4500', '5. volume': '2170350'}, '2026-02-11': {'1. open': '931.0500', '2. high': '936.0000', '3. low': '925.0000', '4. close': '927.0500', '5. volume': '1909603'}, '2026-02-10': {'1. open': '933.4000', '2. high': '941.0000', '3. low': '931.0000', '4. close': '932.1000', '5. volume': '1548899'}, '2026-02-09': {'1. open': '944.0500', '2. high': '950.5500', '3. low': '935.3500', '4. close': '937.2500', '5. volume': '1069386'}, '2026-02-06': {'1. open': '944.9000', '2. high': '947.6000', '3. low': '937.7500', '4. close': '941.1500', '5. volume': '187135'}, '2026-02-05': {'1. open': '953.5000', '2. high': '955.9500', '3. low': '947.0000', '4. close': '949.5000', '5. volume': '4034302'}, '2026-02-04': {'1. open': '949.1500', '2. high': '957.2000', '3. low': '948.7000', '4. close': '953.4500', '5. volume': '1139667'}, '2026-02-03': {'1. open': '980.0000', '2. high': '990.0000', '3. low': '945.0500', '4. close': '948.4000', '5. volume': '1062402'}, '2026-02-02': {'1. open': '914.0500', '2. high': '930.0000', '3. low': '909.9000', '4. close': '927.3000', '5. volume': '668631'}, '2026-01-30': {'1. open': '929.0500', '2. high': '938.9000', '3. low': '927.9500', '4. close': '929.3500', '5. volume': '1197750'}, '2026-01-29': {'1. open': '932.6000', '2. high': '939.0000', '3. low': '924.3000', '4. close': '935.6500', '5. volume': '2401193'}, '2026-01-28': {'1. open': '928.3500', '2. high': '941.4000', '3. low': '928.3500', '4. close': '932.6500', '5. volume': '1325109'}, '2026-01-27': {'1. open': '899.9500', '2. high': '931.0000', '3. low': '899.9000', '4. close': '926.8500', '5. volume': '1083872'}, '2026-01-23': {'1. open': '919.4000', '2. high': '925.9500', '3. low': '909.2500', '4. close': '916.2500', '5. volume': '598461'}, '2026-01-22': {'1. open': '926.2500', '2. high': '928.2500', '3. low': '913.5000', '4. close': '919.4000', '5. volume': '1972674'}, '2026-01-21': {'1. open': '925.0000', '2. high': '932.7000', '3. low': '915.4000', '4. close': '920.1500', '5. volume': '685008'}, '2026-01-20': {'1. open': '927.6500', '2. high': '934.5000', '3. low': '920.0000', '4. close': '931.1500', '5. volume': '4299767'}, '2026-01-19': {'1. open': '938.3000', '2. high': '938.7500', '3. low': '919.4500', '4. close': '927.6000', '5. volume': '1796067'}, '2026-01-16': {'1. open': '924.7500', '2. high': '936.2500', '3. low': '919.5000', '4. close': '931.1500', '5. volume': '1820553'}, '2026-01-14': {'1. open': '932.0000', '2. high': '940.0500', '3. low': '920.2000', '4. close': '926.0000', '5. volume': '1217236'}, '2026-01-13': {'1. open': '945.0500', '2. high': '947.9500', '3. low': '934.0000', '4. close': '937.2500', '5. volume': '742953'}, '2026-01-12': {'1. open': '938.7000', '2. high': '942.0000', '3. low': '929.5500', '4. close': '936.6500', '5. volume': '823824'}, '2026-01-09': {'1. open': '946.4500', '2. high': '950.3500', '3. low': '933.2000', '4. close': '938.7000', '5. volume': '1014507'}, '2026-01-08': {'1. open': '945.0000', '2. high': '952.8500', '3. low': '941.7000', '4. close': '946.6000', '5. volume': '9669961'}, '2026-01-07': {'1. open': '957.2000', '2. high': '957.6000', '3. low': '946.0000', '4. close': '949.1500', '5. volume': '7401483'}, '2026-01-06': {'1. open': '968.4500', '2. high': '968.4500', '3. low': '955.9000', '4. close': '962.4000', '5. volume': '2306092'}, '2026-01-05': {'1. open': '1002.1000', '2. high': '1006.3000', '3. low': '976.3500', '4. close': '977.7000', '5. volume': '1269360'}, '2026-01-02': {'1. open': '990.7500', '2. high': '1003.0000', '3. low': '988.9500', '4. close': '1001.2000', '5. volume': '341045'}, '2026-01-01': {'1. open': '992.0500', '2. high': '997.5000', '3. low': '989.3000', '4. close': '990.7500', '5. volume': '1055343'}, '2025-12-31': {'1. open': '991.6000', '2. high': '997.5000', '3. low': '987.8000', '4. close': '991.7500', '5. volume': '398496'}, '2025-12-30': {'1. open': '991.8500', '2. high': '994.8500', '3. low': '982.2000', '4. close': '990.7000', '5. volume': '662628'}, '2025-12-29': {'1. open': '992.4000', '2. high': '997.3000', '3. low': '987.0000', '4. close': '991.5500', '5. volume': '450062'}, '2025-12-26': {'1. open': '996.0000', '2. high': '997.3000', '3. low': '988.5000', '4. close': '992.4000', '5. volume': '144333'}, '2025-12-24': {'1. open': '994.2000', '2. high': '999.3000', '3. low': '993.2500', '4. close': '997.1000', '5. volume': '448011'}, '2025-12-23': {'1. open': '991.8000', '2. high': '998.5000', '3. low': '987.7000', '4. close': '996.4000', '5. volume': '249755'}, '2025-12-22': {'1. open': '985.9000', '2. high': '992.8000', '3. low': '984.0500', '4. close': '987.4500', '5. volume': '403890'}, '2025-12-19': {'1. open': '983.0000', '2. high': '988.0000', '3. low': '979.0000', '4. close': '985.9500', '5. volume': '943842'}, '2025-12-18': {'1. open': '979.9000', '2. high': '987.3000', '3. low': '976.2500', '4. close': '979.6500', '5. volume': '1528119'}, '2025-12-17': {'1. open': '998.0500', '2. high': '998.0500', '3. low': '980.8500', '4. close': '984.3000', '5. volume': '1068420'}, '2025-12-16': {'1. open': '992.8500', '2. high': '998.5500', '3. low': '991.0000', '4. close': '994.1500', '5. volume': '800750'}, '2025-12-15': {'1. open': '992.0000', '2. high': '1002.0000', '3. low': '991.9500', '4. close': '995.8500', '5. volume': '109101'}, '2025-12-12': {'1. open': '1001.9000', '2. high': '1004.7000', '3. low': '998.0500', '4. close': '1000.2000', '5. volume': '380119'}, '2025-12-11': {'1. open': '990.9500', '2. high': '1002.7000', '3. low': '988.5500', '4. close': '1000.2000', '5. volume': '1479629'}, '2025-12-10': {'1. open': '996.8500', '2. high': '998.6500', '3. low': '985.2000', '4. close': '990.3500', '5. volume': '579203'}, '2025-12-09': {'1. open': '993.8500', '2. high': '1002.7500', '3. low': '993.8500', '4. close': '996.8500', '5. volume': '373651'}, '2025-12-08': {'1. open': '999.0000', '2. high': '1006.3000', '3. low': '997.8000', '4. close': '1003.1000', '5. volume': '201445'}, '2025-12-05': {'1. open': '990.9500', '2. high': '1007.9000', '3. low': '990.9500', '4. close': '1003.1000', '5. volume': '406479'}, '2025-12-04': {'1. open': '998.2500', '2. high': '1004.7500', '3. low': '992.5500', '4. close': '997.2500', '5. volume': '1499772'}, '2025-12-03': {'1. open': '988.4500', '2. high': '1002.3000', '3. low': '987.8500', '4. close': '1000.4500', '5. volume': '573043'}, '2025-12-02': {'1. open': '993.0000', '2. high': '994.5000', '3. low': '985.7000', '4. close': '990.0000', '5. volume': '424122'}, '2025-12-01': {'1. open': '1016.0500', '2. high': '1017.9000', '3. low': '999.4000', '4. close': '1002.5500', '5. volume': '330942'}, '2025-11-28': {'1. open': '1007.9500', '2. high': '1012.0000', '3. low': '1004.3000', '4. close': '1007.0000', '5. volume': '153665'}, '2025-11-27': {'1. open': '1001.0000', '2. high': '1016.8500', '3. low': '1001.0000', '4. close': '1009.2500', '5. volume': '2242837'}, '2025-11-26': {'1. open': '985.0500', '2. high': '1006.9500', '3. low': '983.0000', '4. close': '1003.8500', '5. volume': '1611446'}, '2025-11-25': {'1. open': '1004.0000', '2. high': '1006.0500', '3. low': '988.4000', '4. close': '989.8500', '5. volume': '464725'}, '2025-11-24': {'1. open': '998.2000', '2. high': '1011.0000', '3. low': '994.3500', '4. close': '999.0500', '5. volume': '675044'}, '2025-11-21': {'1. open': '1002.0500', '2. high': '1008.6000', '3. low': '996.5000', '4. close': '998.1500', '5. volume': '833398'}, '2025-11-20': {'1. open': '998.8000', '2. high': '1011.0000', '3. low': '992.1000', '4. close': '1008.8000', '5. volume': '1603223'}, '2025-11-19': {'1. open': '989.9500', '2. high': '996.5000', '3. low': '984.0000', '4. close': '994.6500', '5. volume': '343679'}, '2025-11-18': {'1. open': '997.5000', '2. high': '998.8000', '3. low': '989.0000', '4. close': '991.6000', '5. volume': '289231'}, '2025-11-17': {'1. open': '990.0500', '2. high': '997.9500', '3. low': '985.5500', '4. close': '996.8000', '5. volume': '1934061'}, '2025-11-14': {'1. open': '971.5000', '2. high': '991.5500', '3. low': '971.4500', '4. close': '988.8500', '5. volume': '408881'}, '2025-11-13': {'1. open': '983.7500', '2. high': '990.3000', '3. low': '982.5000', '4. close': '986.8000', '5. volume': '1462892'}, '2025-11-12': {'1. open': '1000.0000', '2. high': '1000.0000', '3. low': '987.3500', '4. close': '989.4500', '5. volume': '493627'}, '2025-11-11': {'1. open': '985.0000', '2. high': '993.2500', '3. low': '978.1500', '4. close': '991.7000', '5. volume': '235562'}, '2025-11-10': {'1. open': '980.0000', '2. high': '991.7500', '3. low': '980.0000', '4. close': '984.3500', '5. volume': '501924'}, '2025-11-07': {'1. open': '984.3000', '2. high': '984.8000', '3. low': '974.5500', '4. close': '982.9000', '5. volume': '611248'}, '2025-11-06': {'1. open': '983.9000', '2. high': '991.0000', '3. low': '974.2000', '4. close': '984.5000', '5. volume': '1294375'}, '2025-11-04': {'1. open': '989.7500', '2. high': '996.7000', '3. low': '983.6500', '4. close': '985.1000', '5. volume': '597421'}, '2025-11-03': {'1. open': '985.5000', '2. high': '994.6500', '3. low': '983.2000', '4. close': '992.5000', '5. volume': '754198'}, '2025-10-31': {'1. open': '994.9000', '2. high': '1004.3500', '3. low': '982.2000', '4. close': '987.6500', '5. volume': '944173'}, '2025-10-30': {'1. open': '1001.0000', '2. high': '1009.7500', '3. low': '997.0000', '4. close': '998.1000', '5. volume': '837299'}}}

                 open       high       low     close   volume
2025-10-30  1001.0000  1009.7500  997.0000  998.1000   837299
2025-10-31   994.9000  1004.3500  982.2000  987.6500   944173
2025-11-03   985.5000   994.6500  983.2000  992.5000   754198
2025-11-04   989.7500   996.7000  983.6500  985.1000   597421
2025-11-06   983.9000   991.0000  974.2000  984.5000  1294375

In [ ]:
print (df_nse)

               open     high      low    close    volume
2025-10-30  36.8000  36.9400  36.5600  36.8800   4950856
2025-10-31  36.3200  36.3800  35.9300  36.2200   3500574
2025-11-03  36.3100  36.7200  36.2500  36.5000   2905007
2025-11-04  36.2300  36.3700  35.9100  36.2400   3778781
2025-11-05  36.1400  36.1900  35.5100  35.8300   4879543
...             ...      ...      ...      ...       ...
2026-03-19  25.8950  27.0000  25.4800  26.1400  32970355
2026-03-20  26.1100  26.1400  25.3900  25.3900  14991502
2026-03-23  25.1600  25.6900  24.7400  25.4000  19046686
2026-03-24  25.2300  25.5300  25.0800  25.1200  13980404
2026-03-25  26.0000  26.3800  25.7500  25.8100  20723415

[100 rows x 5 columns]

Indian stock market is filled with holidays and stuff.

So we create a complete calender range from start date to end date then reindex the stock data into new timeline.

In [ ]:
start_date = df_nse.index.min()
end_date = df_nse.index.max()

full_date_range = pd.date_range(start=start_date, end=end_date, freq='D')

df_nse_reindexed = df_nse.reindex(full_date_range)
df_bse_reindexed = df_bse.reindex(full_date_range)

df_nse_cleaned = df_nse_reindexed.ffill()
df_bse_cleaned = df_bse_reindexed.ffill()

print("df_nse_cleaned:")
print(df_nse_cleaned)

print("\ndf_bse_cleaned")
print(df_bse_cleaned)

df_nse_cleaned:
               open     high      low    close    volume
2025-10-30  36.8000  36.9400  36.5600  36.8800   4950856
2025-10-31  36.3200  36.3800  35.9300  36.2200   3500574
2025-11-01  36.3200  36.3800  35.9300  36.2200   3500574
2025-11-02  36.3200  36.3800  35.9300  36.2200   3500574
2025-11-03  36.3100  36.7200  36.2500  36.5000   2905007
...             ...      ...      ...      ...       ...
2026-03-21  26.1100  26.1400  25.3900  25.3900  14991502
2026-03-22  26.1100  26.1400  25.3900  25.3900  14991502
2026-03-23  25.1600  25.6900  24.7400  25.4000  19046686
2026-03-24  25.2300  25.5300  25.0800  25.1200  13980404
2026-03-25  26.0000  26.3800  25.7500  25.8100  20723415

[147 rows x 5 columns]

df_bse_cleaned
                 open       high       low     close   volume
2025-10-30  1001.0000  1009.7500  997.0000  998.1000   837299
2025-10-31   994.9000  1004.3500  982.2000  987.6500   944173
2025-11-01   994.9000  1004.3500  982.2000  987.6500   944173
2025-11-02   994.9000  1004.3500  982.2000  987.6500   944173
2025-11-03   985.5000   994.6500  983.2000  992.5000   754198
...               ...        ...       ...       ...      ...
2026-03-21   788.0000   794.0000  778.6000  780.4500  5028824
2026-03-22   788.0000   794.0000  778.6000  780.4500  5028824
2026-03-23   766.9500   768.3000  740.9500  743.7500  4002930
2026-03-24   767.7500   772.6000  747.7000  765.1500  2829026
2026-03-25   769.8000   794.8000  768.4000  781.7000  4057883

[147 rows x 5 columns]

## **Saving to CSV**

In [ ]:
df_nse_cleaned.to_csv("nse_data.csv")
df_bse_cleaned.to_csv("bse_data.csv")